Add outputs for VPN gateway and route table
isovalent/terraform-aws-vpc pull request #2
Opened 2022-11-17 19:21 UTC by hhoover

This commit also has README updates for said outputs

2022-11-18 10:10 UTC, bmcustodio requested changes
Couple nits (and you'll likely have to re-run `make docs`).

2022-11-18 10:10 UTC, bmcustodio commented on outputs.tf
> +  description = "The IDs of the created VPN gateway in the VPC."
```suggestion
  description = "The ID of the main route table that has been created."
```

2022-11-18 10:10 UTC, bmcustodio commented on outputs.tf
> +  description = "The IDs of the created VPN gateway in the VPC."
```suggestion
  description = "The ID of the VPN gateway that has been created."
```

2022-11-21 17:23 UTC, hhoover commented
resolved, please re-review 😄

2024-06-12 18:35 UTC, hhoover commented
It would be nice, but looks like I need to update / redo the PR. _sets reminder_

2024-06-18 15:17 UTC, hhoover commented
@bmcustodio done with what's different, please review

2024-07-31 10:49 UTC, PhilipSchmid approved these changes

2024-07-31 10:50 UTC, merged